//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class приходs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public приходs()
        {
            this.приходТоварыs = new HashSet<приходТоварыs>();
        }
    
        public int Id { get; set; }
        public int КодПрихода { get; set; }
        public int ДатаПриходанаСклад { get; set; }
        public string Наименование { get; set; }
        public int СотрудникиID { get; set; }
    
        public virtual сотрудникиs сотрудникиs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<приходТоварыs> приходТоварыs { get; set; }
    }
}
