//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class приходТоварыs
    {
        public int Id { get; set; }
        public int ПриходId { get; set; }
        public int ТоварыId { get; set; }
    
        public virtual приходs приходs { get; set; }
        public virtual товарыs товарыs { get; set; }
    }
}
